# Generated by Django 5.1.1 on 2024-09-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('upCycleRequest', '0004_remove_upcyclerequest_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upCycleRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upCycleRequest.upcyclerequest'),
        ),
    ]
