# Generated by Django 5.1.1 on 2024-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_upcyclerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiresAt',
            field=models.DateTimeField(null=True),
        ),
    ]
