# Generated by Django 5.1.1 on 2024-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_expiresat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiresAt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
