# Generated by Django 5.1.1 on 2024-09-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upCycleRequest', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcyclerequest',
            name='quantity',
        ),
    ]
