# Generated by Django 5.1.1 on 2024-09-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upCycleRequest', '0003_remove_upcyclerequest_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcyclerequest',
            name='items',
        ),
    ]
