# Generated by Django 5.1.1 on 2024-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upCycleRequest', '0004_remove_upcyclerequest_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcyclerequest',
            name='requestsAt',
            field=models.DateField(null=True),
        ),
    ]
